### ISSUE TITLE
IG "Kontext im Gesamtprojekt / Bezüge zu anderen Modulen" sowie "Anwendungsfälle / Informationsmodell " und "Extension Supporting Info"n

### ISSUE THREAD

**Issue by gharoske** [medizininformatik-initiative/kerndatensatzmodul-GenetischeTests#1]
Das Erweiterungsmodul hat ganz offensichtlich auch Bezüge zum Erweiterungsmodul Pathologiebefund. Dies sollte im Text erwähnt werden.

Daraus folgt auch, dass
- im Teil Anwendungsfälle/Informationsmodell der Part "... ist es wichtig anzumerken, dass der behandelnde Mediziner das Gesamtbild zum Patientenbefinden kennt, welches über radiologische Befunde und Kenntnisse der PatientInnenhistorie ..." durch Bezug zum Pathologiebefund ergänzt wird,
- Referenzen zum Pathologie- und Laborbefund ins UML-Diagramm bei Indikation/Anforderung aufgenommen werden,
- für die extension "supporting info" explizit diese essentiellen Referenzen erwähnt werden.

**Comment by CStell01** [comment]
Danke für die Hinweise.
Wir haben wie von Ihnen vorgeschlagen den Text im IG zu den Anwendungsfällen angepasst: "Während einige oder alle dieser Informationen in dem Befund kommuniziert werden können, ist es wichtig anzumerken, dass der behandelnde Mediziner das Gesamtbild zum Patientenbefinden kennt, welches **über Pathologie- und Laborbefunde**, radiologische Befunde und Kenntnisse der PatientInnenhistorie sowie die Auswertung des molekulargenetischen Befundberichtes gebildet wird."
Außerdem wurden die Referenzen im UML ergänzt. Die Referenz auf einen vorherigen Labor- und Pathologiebefundbericht ist über das supportingInfo Datenelement möglich, jedoch muss die Referenz offen gehalten werden (um beispielsweise auch FamilyMemberHistory als supporting Info angeben zu können) und kann nicht durch die Pathologiebefundreferenz allein eingeschränkt werden.
