### ISSUE TITLE
Error in SearchParameter

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-GenetischeTests#11]
https://github.com/medizininformatik-initiative/kerndatensatzmodul-GenetischeTests/blob/d5c87fbc7452a70b031c300b509c2e4e2528c554/input/fsh/SearchParameter.fsh#L76

code is duplicate and breaks the task-reasonreference search param

**Comment by ThomasDeBe** [comment]
was transfered to meta
