### ISSUE TITLE
ClinVar Evidence Level Example Codes inconsistencies with the star-ratings

### ISSUE THREAD

**Issue by RMerdzanic** [medizininformatik-initiative/kerndatensatzmodul-GenetischeTests#2]
The four, three and no star ratings are correctly defined. However, one and two star-ratings could be further specified (i.e. one star does not **only** mean single submitter (as defined in the Implementation guide), but also multiple submitters with the conflicting interpretations. Two star rating means also multiple submitters, but **no conflicts** with the variant interpretation. 

The cited link is broken:"http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/clinvar-evidence-level-custom-cs"

**Comment by julsas** [comment]
> The cited link is broken:"http://hl7.org/fhir/uv/genomics-reporting/CodeSystem/clinvar-evidence-level-custom-cs"

It's not a link. It's a canonical url which does not have to resolve.

> However, one and two star-ratings could be further specified (i.e. one star does not only mean single submitter (as defined in the Implementation guide), but also multiple submitters with the conflicting interpretations.

The CodeSystem is defined by HL7 Clinical Genomics Working Group. The ClinVar source is described here: https://www.ncbi.nlm.nih.gov/clinvar/docs/details/ Seems like the description for one and two star ratings was cut off but the codes represent exact ClinVar concepts.
