### ISSUE TITLE
Variant Inheritance codes to be further specified?

### ISSUE THREAD

**Issue by RMerdzanic** [medizininformatik-initiative/kerndatensatzmodul-GenetischeTests#3]
The named codes for the Variant inheritance value set includes three codes for the variant inheritance: 
"
Code | Display
LA26320-4 | Maternal
LA26321-2 | Paternal
LA4489-6 | Unknown"

The following extension should (at least) be considered; **LA26807-0** _**De novo**_ (from neither of parents) and? LA24789-2 Mitochondrial. Even it is maternal by inheritance, specifying the mitochondrial inheritance might be important. 

Further possible option to consider for complex events is uniparental disomy (UPD), where entire chromosome, or chromosome part is inherited from a single parent (both alleles from a single parent). Codes to be considered here: LP33556-9 Chromosome uniparental disomy and stratified: LP31864-9 Chromosome 7 uniparental disomy; LP33156-8 Chromosome 11 uniparental disomy; LP33047-9 Chromosome 14 uniparental disomy; LP31863-1 Chromosome 15 uniparental disomy.

**Comment by julsas** [comment]
https://chat.fhir.org/#narrow/stream/179197-genomics/topic/variant.20Inherited.20from

Looks like the result from the discussion was to exclude `De novo` as it is not considered a mode of inheritance. The binding strength is extensible though, i.e. other modes of inheritance could be added.
