### ISSUE TITLE
Recommended medications that do not have an ATC code

### ISSUE THREAD

**Issue by hoffmka** [medizininformatik-initiative/kerndatensatzmodul-GenetischeTests#4]
The FHIR profile "Therapeutische Implikation" (https://simplifier.net/medizininformatikinitiative-modulomics/sdmiimolgentherapeutischeimplikation) allows to specify recommended medications, which can be selected from the ATC catalog. What would the process look like if we were recommending medications that do not have an ATC code. For example, for drugs within a clinical trial that do not have an official approval. I see that in the element **Observation.component:medication-assessed.value[x]** is no binding defined. Does this mean that I can also specify medications that are not listed in the ATC catalog? If so, what would that look like specifically in the FHIR resource? And If not, what would be the procedure to add a new medication to the ATC catalog?

**Comment by julsas** [comment]
> What would the process look like if we were recommending medications that do not have an ATC code. For example, for drugs within a clinical trial that do not have an official approval.



You can use any medication terminology system within the `valueCodeableConcept` element. It does not have to be ATC, but to populate the [Coding](https://hl7.org/fhir/datatypes.html#codesystem) inside [CodeableConcept](https://hl7.org/fhir/datatypes.html#codeableconcept), you need a system which is a URI that identifies the code system that defines the code. If that is not possible for drugs within a clinical trial, `CodeableConcept` can also be just text.



```json
"valueCodeableConcept": {
        "text": "uncoded free text result"
    }
```



> Does this mean that I can also specify medications that are not listed in the ATC catalog?



Yes, any terminology system is possible here.



> If so, what would that look like specifically in the FHIR resource?



```json
      "valueCodeableConcept": {
        "coding": [
          {
            "code": "L01EC",
            "system": "http://www.whocc.no/atc",
            "display": "B-Raf serine-threonine kinase (BRAF) inhibitors"
          },
          {
            "code": "703645005",
            "system": "http://snomed.info/sct",
            "display": "Product containing B-Raf inhibitor (product)"
          }
        ],
        "text": "BRAF Inhibitor"
      }
```
`valueCodeableConcept` is an array that can be extended. Plus you can have free text inside `.text` element.

> And If not, what would be the procedure to add a new medication to the ATC catalog?

Seems to be out of scope here, but probably submit a request to WHO https://www.whocc.no/atc/application_for_atc_codes/ or BfArM in Germany.
