### ISSUE TITLE
Observation.component:allelic-state.value[x] valueset extension?

### ISSUE THREAD

**Issue by RMerdzanic** [medizininformatik-initiative/kerndatensatzmodul-GenetischeTests#5]
Gemäß HL7 FHIR ist Observation.component:allelic-state.value[x] [LOINC LL381-5](http://loinc.org/vs/LL381-5) valuesets erfasst, und zwar:         "code": "LA6703-8",
        "display": "Heteroplasmic"
   
        "code": "LA6704-6",
        "display": "Homoplasmic"
    
        "code": "LA6705-3",
        "display": "Homozygous"
 
        "code": "LA6706-1",
        "display": "Heterozygous"
  
        "code": "LA6707-9",
        "display": "Hemizygous"

Wir müssten noch daran auf "**Compund heterozygous**" state denken. Wir werden es auf jeden Fall bei Fällen mit autosomal-rezessivem Erbgang benötigen. Fachleute könnten auch argumentieren, wenn sie bestätigt oder vermutet werden (nur bestätigter CH-Status bestätigt genetische Diagnose).

**Comment by julsas** [comment]
Abbildung von Compound Heterozygous erfolgt über zwei Variant Instanzen, wie hier beschrieben: http://hl7.org/fhir/uv/genomics-reporting/sequencing.html#representing-compound-heterozygotes
